# Generated by Django 6.0.3 on 2026-04-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='title',
        ),
    ]
