# Generated by Django 6.0.3 on 2026-04-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_tasks_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
